<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[3]=array(0,1,1,'5qGI5L6L5bGV56S6');
$cfg_Cs[4]=array(3,1,1,'546w5Luj6aOO5qC8');
$cfg_Cs[5]=array(3,1,1,'5qyn5byP6aOO5qC8');
$cfg_Cs[6]=array(3,1,1,'5Lit5byP6aOO5qC8');
$cfg_Cs[7]=array(3,1,1,'6Ziz5Y+w6aOO5qC8');
$cfg_Cs[9]=array(0,1,1,'5oub5ZWG5Yqg55uf');
$cfg_Cs[23]=array(0,1,1,'5Zui6Zif6aOO6YeH');
$cfg_Cs[14]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[19]=array(0,1,1,'6aaW6aG15bm754Gv');
$cfg_Cs[20]=array(2,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[21]=array(2,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[27]=array(0,1,1,'5Zui6Zif6aOO6YeH');
?>