<?php
$z[0]=Array("field","",279,310);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",363,392);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n              <li>\r\n                <div class=\"nimg col-md-3 col-sm-3 hidden-xs\"><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\"></a></div>\r\n                <div class=\"newdec col-md-9 col-sm-9 col-xs-12\">\r\n                  <div class=\"time tc col-md-2 col-sm-2 col-xs-3\"><span>[field:pubdate function=\"MyDate('d',@me)\"/]</span><br>\r\n                    [field:pubdate function=\"MyDate('Y-m',@me)\"/]</div>\r\n                  <div class=\"descript col-md-10 col-sm-10 col-xs-9\">\r\n                    <dd><a href=\"[field:arcurl/]\">[field:title/]</a></dd>\r\n                    <dt>[field:description function=\"cn_substr(@me,300)\"/]...</dt>\r\n                  </div>\r\n                </div>\r\n              </li>\r\n              ",454,1255);
$z[2][4]=array();
$z[2][4]['row']="2";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("field","",1297,1325);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>