<?php
$z[0]=Array("arclist","\r\n                  <div class=\"pro1 col-md-7 col-sm-7 col-xs-12 slideInLeft wow animated\"> <a href='[field:arcurl/]'><img src='[field:picname/]'>\r\n                    <p class=\"p_title transition\">[field:title/]</p>\r\n                    </a></div>\r\n                  ",20,343);
$z[0][4]=array();
$z[0][4]['limit']="0,1";
$z[0][4]['titlelen']="50";
$z[1]=Array("arclist","\r\n                  <div class=\"pro1 pro2 col-md-5 col-sm-5 col-xs-6 slideInRight wow animated\"> <a href='[field:arcurl/]'><img src='[field:picname/]'>\r\n                    <p class=\"p_title transition\">[field:title/]</p>\r\n                    </a></div>\r\n                  ",363,691);
$z[1][4]=array();
$z[1][4]['limit']="1,1";
$z[1][4]['titlelen']="50";
$z[2]=Array("arclist","\r\n                  <div class=\"pro1 pro3 col-md-4 col-sm-4 col-xs-6 slideInUp wow animated\"> <a href='[field:arcurl/]'><img src='[field:picname/]'>\r\n                    <p class=\"p_title transition\">[field:title/]</p>\r\n                    </a></div>\r\n                  ",711,1036);
$z[2][4]=array();
$z[2][4]['limit']="2,1";
$z[2][4]['titlelen']="50";
$z[3]=Array("field","",1108,1136);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>