<div class="detil"> {dede:arclist limit='0,1' titlelen='50'}
                  <div class="pro1 col-md-7 col-sm-7 col-xs-12 slideInLeft wow animated"> <a href='[field:arcurl/]'><img src='[field:picname/]'>
                    <p class="p_title transition">[field:title/]</p>
                    </a></div>
                  {/dede:arclist}
                  {dede:arclist limit='1,1' titlelen='50'}
                  <div class="pro1 pro2 col-md-5 col-sm-5 col-xs-6 slideInRight wow animated"> <a href='[field:arcurl/]'><img src='[field:picname/]'>
                    <p class="p_title transition">[field:title/]</p>
                    </a></div>
                  {/dede:arclist}
                  {dede:arclist limit='2,1' titlelen='50'}
                  <div class="pro1 pro3 col-md-4 col-sm-4 col-xs-6 slideInUp wow animated"> <a href='[field:arcurl/]'><img src='[field:picname/]'>
                    <p class="p_title transition">[field:title/]</p>
                    </a></div>
                  {/dede:arclist}
                  <div class="col-md-12 col-sm-12 col-xs-12"><a href='{dede:field name='typeurl'/}' class="more db"><span>Read more</span></a></div>
                </div>