<li class="col-md-12 col-sm-12 col-xs-12">
              <div class="nimg col-md-4 col-sm-4 col-xs-12"><a href="[field:arcurl/]"><img src="[field:picname/]"></a></div>
              <div class="newdec2 col-md-8 col-sm-8 col-xs-12">
                <dd><a href="[field:arcurl/]">[field:title/]</a></dd>
                <dt>[field:description function="cn_substr(@me,400)"/]...</dt>
                <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span> </div>
            </li>