<?php
$z[0]=Array("arcurl","",113,128);
$z[0][4]=array();
$z[1]=Array("picname","",140,156);
$z[1][4]=array();
$z[2]=Array("arcurl","",264,279);
$z[2][4]=array();
$z[3]=Array("title","",281,295);
$z[3][4]=array();
$z[4]=Array("description","",326,376);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,400)";
$z[5]=Array("pubdate","",408,455);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y-m-d',@me)";

?>