<?php
$z[0]=Array("field","",91,149);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("field","",155,215);
$z[1][4]=array();
$z[1][4]['name']="typeid";
$z[1][4]['function']="GetTopTypenameen(@me)";
$z[2]=Array("field","",345,374);
$z[2][4]=array();
$z[2][4]['name']="position";
$z[3]=Array("channel","\r\n    <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n    ",465,664);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";

?>